### ISSUE TITLE
quality control error

### ISSUE THREAD

**Issue by Schneider32** [jrigden/BeigeOrion#5]
In the data evaluation and the evaluation of the quality is an error in the source code. The data are taken correctly on botometers but the evaluation is pushed incorrectly into the database.

![3222](https://user-images.githubusercontent.com/18450785/37952979-da23c43a-31a1-11e8-91dc-8d99bbb17122.JPG)
![2222](https://user-images.githubusercontent.com/18450785/37952985-dd5425a0-31a1-11e8-978d-047b6adbdfe1.JPG)

**Comment by Schneider32** [comment]
import time
import models
from utils import *
def get_all_relationships(screen_name):
    subject = models.Subject.get(models.Subject.screen_name == screen_name)
    relationships = models.Relationship.select().where(
        models.Relationship.subject == subject)
    return relationships
def get_subject_follower_quality(screen_name):
    logger.info('Checking Quality for subject: {}'.format(screen_name))
    **chunk = 1 / 6 ---> **0.166666666** <--- is working**
    quality = {} 
    quality['no_timeline'] = 0
    quality['protected'] = 0
    quality['very_good'] = 0
    quality['good'] = 0
    quality['neutral'] = 0
    quality['poor'] = 0
    quality['very_poor'] = 0
    quality['total'] = 0

**Comment by mr-rigden** [comment]
I don't understand this issue. Could you please try to reexplain it.

**Comment by Schneider32** [comment]
The problem is that the operation chunk = 1/6 is not executed properly and therefore every user is very_poor. I change 1/6 to 0.1666 .. the code works

**Comment by mr-rigden** [comment]
This is a Python 2 vs Python 3 issue related to [PEP 238](https://www.python.org/dev/peps/pep-0238/).
```
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> a = 1 / 6
>>> a
0
```

```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> a = 1 / 6
>>> a
0.16666666666666666

```

Python 2 is reaching [end of life](https://pythonclock.org/) and is not supported by this project.
